// Regenerates src/abi.ts from compiled Hardhat artifacts.
// Usage: npx hardhat compile && node scripts/gen-abi.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const load = (p) => JSON.parse(readFileSync(new URL(p, import.meta.url), 'utf8'));
const usdc = load('../artifacts/contracts/MockUSDC.sol/MockUSDC.json');

const out = `// GENERATED by scripts/gen-abi.mjs from Hardhat artifacts — do not edit by hand.
// Regenerate: npx hardhat compile && node scripts/gen-abi.mjs

export const MOCK_USDC_ABI = ${JSON.stringify(usdc.abi, null, 2)} as const;

export const MOCK_USDC_BYTECODE = ${JSON.stringify(usdc.bytecode)} as const;
`;
writeFileSync(new URL('../src/abi.ts', import.meta.url), out);
console.log('wrote src/abi.ts');
